version: 1
terminal: yakuake
variables:
  path: /var/www/projects/work/totalAssesment/dashboard 
pre:
  - cd %path%
  - sleep 3
  - echo PATH

tabs:
  dev:
    - "cd %path%"
    - "git status"
  htop:
    - "htop"
  www:
    - "jump www"
  split:
    left:
      top:
        - "jump ta"
      bottom: 
        - "jump www"
    right:
      - "ps faux"
  server:
    - ssh server.server
down:
  - cd %path%
  - docker-compose stop